#!/bin/bash

# Takes input of on/off and switches Synaccess PDU and SDWire3 appropriately.

# TODO: Get rid of the sleeps once sdwire accepts --wait

if [ "${1}" = "on" ]; then
	sdwire switch target
	sleep 2
	synpdu 1 on
elif [ "${1}" = "off" ]; then
	synpdu 1 off
	sleep 1
	sdwire switch host
	sleep 2
	sdwire list
else
	echo "Error: must request 'on' or 'off'"
	exit 1
fi
